services:
  chalpal:
    image: chalpal:latest  # Replace with the actual image name for your Spring Boot app
    ports:
      - "8080:8080"  # Adjust the ports as needed
    environment:
      - POSTGRES_DB=jdbc:postgresql://postgres:5432/mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase  # Replace "mydatabase" with your database name
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"  # Map PostgreSQL container's port 5432 to the host
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Store PostgreSQL data

volumes:
  postgres-data:
