name: Unit test - PR
run-name: (PR - ${{ github.head_ref }} -> ${{ github.base_ref }}) - Unit testing

on:
  pull_request:
    branches: main

jobs:
  pr-unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven

      - name: Verify with Maven
        run: mvn clean verify

      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: target/surefire-reports